export enum ENUM_USER_POWER {
  DASHBOARD = 'DASHBOARD',
  TRANSACTION = 'TRANSACTION',
  BRANCH = 'BRANCH',
  DEPARTMENT = 'DEPARTMENT',
  USERS = 'USERS',
  COMPANY = 'COMPANY',
  REQUISITION = 'REQUISITION',
  ATTENDANCE = 'ATTENDANCE',
  LEAVE = 'LEAVE',
  TEAM = 'TEAM',
}
