export enum ENUM_USER_ROLE {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ADMIN = 'ADMIN',
  EMPLOYEE = 'EMPLOYEE',
  HR = 'HR',
  INCHARGE = 'INCHARGE',
  MANAGER = 'MANAGER',
}

export enum ENUM_USER_STATUS {
  ACTIVATE = 'ACTIVATE',
  DEACTIVATE = 'DEACTIVATE',
}
export enum ENUM_USER_GENDER {
  MALE = 'MALE',
  FEMALE = 'FEMALE',
}
export enum ENUM_USER_EXIT_TYPE {
  TERMINATED = 'TERMINATED',
  RESIGNED = 'RESIGNED',
}
